In [254]:
import numpy as np

In [255]:
cars = ['1', '3', '4', '6', '7', '12', '14', '15', '17', '18', 
        '19', '20', '21', '22', '23', '24', '25', '26', '27', 
        '28', '29', '59', '60', '64', '66', '88', '98']
detectors = ['numenta', 'random', 'bayes', 'expose']
thresholds = ['0.36', '0.997', '0.39', '0.992']

In [127]:
print(detectors)
for car in cars:
    labels = np.loadtxt('labels/indy2018-' + car + '-labels.txt')
    events = np.array(list(set(labels.flatten())))
    
    counts = []
    accurs = []
    for i in range(len(detectors)):
        result = np.loadtxt('results/' + detectors[i] + 
                            '/anomaly_' + thresholds[i] + 
                            '_indy2018-' + car + '-vspeed.csv')
        mask = result[:, 2] == 1
        anomaly = result[mask]
        speeds = anomaly[:, 0]
        
        match = np.sum(abs(speeds[None, :] - events[:, None]) < 1000, axis=1)
        count = np.sum(match >= 1)
        accur = count / events.shape[0]
        counts.append(count)
        accurs.append(accur)
    
    print('car ' + car, counts, events.shape[0])
    

['numenta', 'random', 'bayes', 'expose']
car 1 [5, 0, 15, 8] 31
car 3 [1, 1, 9, 2] 19
car 4 [2, 1, 8, 2] 23
car 6 [1, 3, 13, 1] 21
car 7 [4, 0, 17, 2] 29
car 12 [1, 1, 11, 3] 25
car 14 [5, 1, 10, 1] 29
car 15 [2, 1, 12, 0] 18
car 17 [1, 0, 13, 3] 19
car 18 [4, 1, 9, 2] 17
car 19 [2, 0, 14, 3] 27
car 20 [7, 0, 12, 4] 25
car 21 [2, 0, 13, 3] 29
car 22 [4, 1, 12, 4] 23
car 23 [2, 0, 17, 2] 27
car 24 [1, 1, 10, 2] 23
car 25 [6, 0, 15, 4] 23
car 26 [3, 0, 21, 2] 33
car 27 [2, 3, 12, 3] 19
car 28 [3, 0, 12, 0] 19
car 29 [3, 0, 8, 2] 19
car 59 [4, 0, 12, 0] 17
car 60 [2, 2, 10, 4] 19
car 64 [2, 1, 12, 2] 19
car 66 [4, 2, 10, 5] 19
car 88 [1, 2, 9, 1] 21
car 98 [4, 1, 17, 3] 31


#### test 1

In [256]:
text = np.loadtxt('results/numenta/anomaly_0.36_indy2018-1-vspeed.csv')
text.shape

(67372, 3)

In [257]:
mask = text[:, 2] == 1 
mask.shape

(67372,)

In [258]:
anomaly = text[mask]
anomaly.shape

(202, 3)

In [259]:
speeds = anomaly[:, 0]
speeds.shape

(202,)

In [260]:
labels = np.loadtxt('labels/indy2018-1-labels.txt')
labels.shape

(16, 2)

In [261]:
events = np.array(list(set(labels.flatten())))
events.shape

(31,)

In [262]:
match = np.sum(abs(speeds[None, :] - events[:, None]) < 2000, axis=1)
match.shape

(31,)

In [263]:
count = np.sum(match >= 1)
count

9

In [264]:
accur = count / events.shape[0]
accur

0.2903225806451613

#### Test 2

In [113]:
for car in cars:
    labels_test = np.loadtxt('labels/indy2018-' + car + '-labels.txt')
    print(len(set(labels_test.flatten())))

31
19
23
21
29
25
29
18
19
17
27
25
29
23
27
23
23
33
19
19
19
17
19
19
19
21
31


#### Test 3

In [265]:
text = np.loadtxt('results/numenta/anomaly_0.36_indy2018-1-vspeed.csv')

In [266]:
text[:3]

array([[5.8980567e+07, 1.5667000e+02, 0.0000000e+00],
       [5.8980660e+07, 1.5851000e+02, 0.0000000e+00],
       [5.8980754e+07, 1.5710000e+02, 0.0000000e+00]])

In [267]:
mask = text[:, 2] == 1 

In [268]:
anomaly = text[mask]

In [269]:
speeds = anomaly[:, 0]

In [270]:
speeds

array([58980837., 58981092., 58981259., 58981623., 58981809., 58982334.,
       58982427., 58982511., 58982688., 58982781., 58983576., 58984017.,
       58984650., 58985362., 58985539., 58986250., 60234323., 60234509.,
       60234602., 60234690., 60235295., 60235388., 60310748., 60311087.,
       60311534., 60316423., 60338286., 60338547., 60339342., 60353288.,
       60353568., 60355466., 60356178., 60365338., 60365524., 60367208.,
       60367301., 60367488., 60990802., 60996233., 60996326., 61259442.,
       61269507., 61271209., 61271581., 61271670., 61748720., 61748813.,
       61752021., 61752208., 61752394., 61753105., 61753198., 61755924.,
       61756273., 61756738., 61756831., 61757170., 61757254., 61757347.,
       61757440., 61769887., 61770132., 61770225., 61770411., 61770598.,
       61879165., 61879249., 61879426., 61879519., 61880854., 61886891.,
       61887053., 61887137., 61887230., 61888370., 61890239., 61890612.,
       61892742., 61895146., 61895239., 62584547., 

In [271]:
labels = np.loadtxt('labels/indy2018-1-labels.txt')

In [272]:
labels

array([[60233000., 60293000.],
       [60340000., 60345000.],
       [60992000., 61261000.],
       [61261000., 61266000.],
       [61316000., 61745000.],
       [61886000., 62355000.],
       [62587000., 62640000.],
       [62803000., 62810000.],
       [64296000., 64301000.],
       [65748000., 65755000.],
       [65872000., 65983000.],
       [66509000., 66513000.],
       [66566000., 67126000.],
       [67255000., 67849000.],
       [68260000., 68265000.],
       [69018000., 69467000.]])

In [273]:
tol = 0

In [274]:
mask1 = speeds >= labels[0, 0] - tol
mask2 = speeds <= labels[-1, 1] + tol
maskS = mask1 & mask2
middle = speeds[maskS]
middle.shape

(167,)

In [275]:
middle

array([60234323., 60234509., 60234602., 60234690., 60235295., 60235388.,
       60310748., 60311087., 60311534., 60316423., 60338286., 60338547.,
       60339342., 60353288., 60353568., 60355466., 60356178., 60365338.,
       60365524., 60367208., 60367301., 60367488., 60990802., 60996233.,
       60996326., 61259442., 61269507., 61271209., 61271581., 61271670.,
       61748720., 61748813., 61752021., 61752208., 61752394., 61753105.,
       61753198., 61755924., 61756273., 61756738., 61756831., 61757170.,
       61757254., 61757347., 61757440., 61769887., 61770132., 61770225.,
       61770411., 61770598., 61879165., 61879249., 61879426., 61879519.,
       61880854., 61886891., 61887053., 61887137., 61887230., 61888370.,
       61890239., 61890612., 61892742., 61895146., 61895239., 62584547.,
       62584639., 62586639., 62586732., 62800927., 62801172., 62804321.,
       62812051., 62813661., 64150406., 64150499., 64150593., 64150863.,
       64293399., 64296259., 64296352., 64315921., 

In [233]:
j = 0
counts = [0] * labels.shape[0]
for i in range(middle.shape[0]):
    if middle[i] < labels[j, 0] - tol:
        continue
    elif middle[i] >= labels[j, 0] - tol and \
              middle[i] <= labels[j, 1] + tol:
        counts[j] += 1
    elif middle[i] > labels[j, 1] + tol:
        j += 1
        i -= 1
    else:
        print('in else')
    if j == labels.shape[0]:
        # print('end of labels')
        break
        
counts

[6, 3, 4, 0, 2, 10, 3, 4, 3, 0, 11, 3, 0, 2, 3, 7]

In [237]:
miss = middle.shape[0] - sum(counts)
miss, middle.shape[0]

(106, 167)

In [238]:
match = sum([1 for cnt in counts if cnt > 0])
match, labels.shape[0]

(13, 16)

In [230]:
accur = match / labels.shape[0]
accur

0.8125

In [240]:
fp = miss / middle.shape[0]
fp

0.6347305389221557

#### New method

In [247]:
car = '1'
#for car in cars:
labels = np.loadtxt('labels/indy2018-' + car + '-labels.txt')
events = np.array(list(set(labels.flatten())))

counts = []
accurs = []
for i in range(len(detectors)):
    result = np.loadtxt('results/' + detectors[i] + 
                        '/anomaly_' + thresholds[i] + 
                        '_indy2018-' + car + '-vspeed.csv')
    mask = result[:, 2] == 1
    anomaly = result[mask]
    speeds = anomaly[:, 0]

    match = np.sum(abs(speeds[None, :] - events[:, None]) < 1000, axis=1)
    count = np.sum(match >= 1)
    accur = count / events.shape[0]
    counts.append(count)
    accurs.append(accur)

print('car ' + car, counts, events.shape[0])

car 1 [5, 0, 15, 8] 31
